using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Kirana.Application.Customers;
using Kirana.Domain.Entities;

namespace Kirana.App.ViewModels;

/// <summary>Backs the Add/Edit Customer dialog (PRD §30). The Customer ID is generated by the
/// service and shown read-only when editing — it is never user-editable.</summary>
public sealed partial class CustomerEditViewModel : ObservableObject
{
    private readonly CustomersViewModel _owner;
    private readonly int? _editingCustomerId;

    public bool IsEditMode => _editingCustomerId is not null;

    public string DialogTitle => IsEditMode ? "Edit Customer" : "Add Customer";

    public string CustomerCode { get; } = string.Empty;

    public bool HasCustomerCode => CustomerCode.Length > 0;

    [ObservableProperty]
    private string _name = string.Empty;

    [ObservableProperty]
    private string _phone = string.Empty;

    [ObservableProperty]
    private string _address = string.Empty;

    [ObservableProperty]
    private string _gstin = string.Empty;

    [ObservableProperty]
    private string _notes = string.Empty;

    [ObservableProperty]
    private string? _errorMessage;

    public CustomerEditViewModel(CustomersViewModel owner, Customer? existingCustomer)
    {
        _owner = owner;

        if (existingCustomer is not null)
        {
            _editingCustomerId = existingCustomer.Id;
            CustomerCode = existingCustomer.CustomerCode;
            Name = existingCustomer.Name;
            Phone = existingCustomer.Phone ?? string.Empty;
            Address = existingCustomer.Address ?? string.Empty;
            Gstin = existingCustomer.Gstin ?? string.Empty;
            Notes = existingCustomer.Notes ?? string.Empty;
        }
    }

    [RelayCommand]
    private async Task SaveAsync()
    {
        ErrorMessage = null;

        try
        {
            if (IsEditMode)
            {
                await _owner.UpdateCustomerAsync(_editingCustomerId!.Value, new UpdateCustomerRequest
                {
                    Name = Name,
                    Phone = Phone,
                    Address = Address,
                    Gstin = Gstin,
                    Notes = Notes,
                    PerformedByUserId = _owner.CurrentUserId,
                });
            }
            else
            {
                await _owner.CreateCustomerAsync(new CreateCustomerRequest
                {
                    Name = Name,
                    Phone = Phone,
                    Address = Address,
                    Gstin = Gstin,
                    Notes = Notes,
                    PerformedByUserId = _owner.CurrentUserId,
                });
            }
        }
        catch (Exception ex)
        {
            ErrorMessage = ex.Message;
        }
    }
}
