namespace Kirana.Application.Customers;

/// <summary>Input for creating a customer (PRD §30). CustomerCode is generated by the service.</summary>
public sealed class CreateCustomerRequest
{
    public required string Name { get; init; }
    public string? Phone { get; init; }
    public string? Address { get; init; }
    public string? Gstin { get; init; }
    public string? Notes { get; init; }
    public int? PerformedByUserId { get; init; }
}
