using Kirana.Domain.Entities;
using Kirana.Domain.Taxation;

namespace Kirana.Application.Customers;

/// <summary>Input for creating a customer (PRD §30). CustomerCode is generated by the service.</summary>
public sealed class CreateCustomerRequest
{
    public required string Name { get; init; }
    public string? Phone { get; init; }
    public string? Address { get; init; }
    public string? Gstin { get; init; }
    public string? StateCode { get; init; }
    public GstRegistrationType? GstRegistrationType { get; init; }
    public string? Notes { get; init; }

    /// <summary>Optional POS default (Phase 15B-4). Null = no preference; bills open at Retail.</summary>
    public PriceLevel? DefaultPriceLevel { get; init; }

    public int? PerformedByUserId { get; init; }
}
