namespace Kirana.Application.Purchasing;

/// <summary>Input for creating a supplier (PRD §28-29). SupplierCode is generated by the service.</summary>
public sealed class CreateSupplierRequest
{
    public required string Name { get; init; }
    public string? Gstin { get; init; }
    public string? ContactPerson { get; init; }
    public string? Phone { get; init; }
    public string? Email { get; init; }
    public string? Address { get; init; }
    public int? PerformedByUserId { get; init; }
}
